### ISSUE TITLE
Some paths intersect incorrectly

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/vfit#5]
Sometimes paths intersect incorrectly in the static output. I'm not sure what causes this but it appears to be caused by the instancing process.

## This issue only appears on Mac as far as I can tell!

![image](https://user-images.githubusercontent.com/41548458/103365823-f455b080-4a8e-11eb-9ebe-0b0317208f92.png)

**Comment by jonpalmisc** [comment]
@ViktorRubenko Any idea what might be causing this?

**Comment by ViktorRubenko** [comment]
Variable fonts may have unmerged outlines for better variations. 
Unlike vars, static outlines must be merged.

**Comment by jonpalmisc** [comment]
> Variable fonts may have unmerged outlines for better variations.
> Unlike vars, static outlines must be merged.

@ViktorRubenko Can this be done with fonttools to correct this issue automatically?

**Comment by ViktorRubenko** [comment]
@jonpalmisc 
don't know how to merge contours via fontTools, but you can try this
https://github.com/fonttools/fonttools/issues/1281#issuecomment-466772626

to merge contours you can use this 
https://github.com/fonttools/skia-pathops
but if a font has hinting, results might be unpredictable
