### ISSUE TITLE
not getting the results i'd like to

### ISSUE THREAD

**Issue by alexmyczko** [jonpalmisc/vfit#9]
i have tried your sample.json on these fonts:

https://sid.ethz.ch/debian/fonts-homecomputer/fonts-homecomputer-1.0/temp_out/

but i'd rather like to get results like
https://sid.ethz.ch/debian/fonts-homecomputer/fonts-homecomputer-1.0/demo-workbench.html

it's pretty near, but i'm not sure... maybe you have a trick/tip how to improve the sample.json?

**Comment by jonpalmisc** [comment]
Can you provide the JSON config you used as well as an image of the result so I can better understand the issue?

**Comment by alexmyczko** [comment]
Of course, the json is the original sample.json same url: https://sid.ethz.ch/debian/fonts-homecomputer/fonts-homecomputer-1.0/temp_out/config.json

and images i have to create... will edit/add here
<img width="365" alt="Screenshot 2021-12-15 at 13 13 29" src="https://user-images.githubusercontent.com/21078693/146184693-9842b749-3164-4c55-bbdc-772bbb0e7de2.png">

**Comment by jonpalmisc** [comment]
<img width="712" alt="image" src="https://user-images.githubusercontent.com/41548458/146369146-bc3a4d08-ecf9-4a8b-9a02-2fcf56f10d5c.png">

Could you elaborate more on what you are expecting to see? In the image above, the left is the site you sent and on the right is the output of VFIT viewed with Font Book — I think they look nearly identical. In both cases, I used the same settings. You can see the JSON config I used below.

```json
[
  {
    "family": "Amiga",
    "axes": {
      "wght": 400.0,
      "wdth": 100.0
    },
    "prefFamily": "Amiga",
    "prefSubfamily": "Regular",
    "weightOverride": 400,
    "widthOverride": 5
  }
]
```

**Comment by alexmyczko** [comment]
You absolutely right. I was only irritated to see the font way too large, instead of the usualy very small in terminals used... thanks for vfit! I've made a debian package of it :)

fits very well to `fnt`: https://github.com/alexmyczko/fnt that is able to download google web fonts (vf) to be later used not only on the web...
